version: '3.7'

services:
  loadbalance:
    image: nginx:1.13.1
    restart: always
    container_name: laravel-loadbalance-prod
    depends_on:
      - laravel
      - socketio
    expose:
      - 80
      - 443
    ports:
      - 2395:80
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      proxy:
      default:
        aliases:
          - laravelnginx

  laravel:
    image: laravel-prod
    container_name: laravel-prod
    restart: always
    depends_on:
      - mysql
      - redis
      - socketio
    networks:
      default:
        aliases:
          - laravel
    volumes:
     - ./app/storage:/app/storage
     - ./app/public:/app/public
     - ./conf/php-add.ini:/usr/local/etc/php/conf.d/php-add.ini
     - ./conf/.env:/app/.env
     - ./mail:/etc/ssmtp
     - ./worker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
     - /etc/localtime:/etc/localtime:ro
    expose:
      - 9000

  laravel_worker:
    image: laravel-prod
    container_name: laravel-worker-prod
    restart: always
    depends_on:
      - mysql
      - redis
      - socketio
      - laravel
    entrypoint:
      - bash
      - -c
      - |
        set -e
        echo 'Starting queue workers and scheduler'
        /start.sh
        echo 'Starting php-fpm'
        exec php-fpm
    networks:
      default:
        aliases:
          - laravel_worker
    volumes:
     - ./app/storage:/app/storage
     - ./app/public:/app/public
     - ./conf/php-add.ini:/usr/local/etc/php/conf.d/php-add.ini
     - ./conf/.env:/app/.env
     - ./mail:/etc/ssmtp
     - ./worker/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf:ro
     - ./worker/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
     - /etc/localtime:/etc/localtime:ro
    expose:
      - 9000

  mysql:
    image: mariadb:10.4.11
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel-mysql-prod
    networks:
      default:
        aliases:
          - mysql
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:5.0.7
    container_name: laravel-redis-prod
    restart: always
    networks:
      default:
        aliases:
          - redis
    volumes:
      - ./redis:/data
      - /etc/localtime:/etc/localtime:ro

  socketio:
    image: mintopia/laravel-echo-server
    restart: always
    container_name: laravel-socketio-prod
    depends_on:
      - redis
    networks:
      default:
        aliases:
          - socketio
    volumes:
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 6001
    environment:
      - LARAVEL_ECHO_SERVER_AUTH_HOST=http://laravelnginx
      - LARAVEL_ECHO_SERVER_DEBUG=false
      - ECHO_DEVMODE=false
      - ECHO_PROTOCOL=http
      - ECHO_REDIS_PORT=6379
      - ECHO_REDIS_HOSTNAME=redis
      - ECHO_ALLOW_CORS
      - ECHO_ALLOW_ORIGIN

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
  proxy:
    external:
      name: nginx-proxy
